In [4]:
import numpy as np

In [33]:
a = np.array([[1, 6],[2, 8], [3, 11], [3, 10], [1 ,7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [36]:
a.shape, a.ndim, a.size

((5, 2), 2, 10)

In [45]:
a.mean(axis=0)

array([2. , 8.4])

In [87]:
a_centered=a-a.mean(axis=0)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [88]:
a_centered_sp=np.dot(a_centered[:,0],a_centered[:,1]).copy()
a_centered[:,0], a_centered[:,1], a_centered_sp

(array([-1.,  0.,  1.,  1., -1.]), array([-2.4, -0.4,  2.6,  1.6, -1.4]), 8.0)

In [94]:
a_centered_sp/(a.shape[0]-1)

2.0

In [102]:
np.cov(a.transpose()), np.cov(a.transpose())[0, 1]

(array([[1. , 2. ],
        [2. , 4.3]]),
 2.0)

In [104]:
import pandas as pd

In [110]:
a = {"a_i":[1, 2, 3],"a_n":['Тургенев','Чехов','Островский']}
authors = pd.DataFrame(a)
authors

a_i         a_n
0    1    Тургенев
1    2       Чехов
2    3  Островский

In [112]:
book = pd.DataFrame({"a_i":[1, 1, 1, 2, 2, 3, 3],"b_t":['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],"p":[450, 300, 350, 500, 450, 370, 290]})
book

a_i                   b_t    p
0    1           Отцы и дети  450
1    1                 Рудин  300
2    1     Дворянское гнездо  350
3    2      Толстый и тонкий  500
4    2       Дама с собачкой  450
5    3                 Гроза  370
6    3  Таланты и поклонники  290

In [114]:
df_a_p = pd.merge(authors, book, on='a_i', how='inner')
df_a_p

a_i         a_n                   b_t    p
0    1    Тургенев           Отцы и дети  450
1    1    Тургенев                 Рудин  300
2    1    Тургенев     Дворянское гнездо  350
3    2       Чехов      Толстый и тонкий  500
4    2       Чехов       Дама с собачкой  450
5    3  Островский                 Гроза  370
6    3  Островский  Таланты и поклонники  290

In [115]:
df_t5=df_a_p.nlargest(5, "p")
df_t5

a_i         a_n                b_t    p
3    2       Чехов   Толстый и тонкий  500
0    1    Тургенев        Отцы и дети  450
4    2       Чехов    Дама с собачкой  450
5    3  Островский              Гроза  370
2    1    Тургенев  Дворянское гнездо  350

In [119]:
df_a_s=df_t5.groupby('a_n').agg({'p':['min', 'max', 'mean']})
df_a_s

p          
            min  max mean
a_n                      
Островский  370  370  370
Тургенев    350  450  400
Чехов       450  500  475

In [122]:
df_a_s.columns

MultiIndex([('p',  'min'),
            ('p',  'max'),
            ('p', 'mean')],
           )

In [123]:
df_a_s.loc[:,('p', 'min')]

a_n
Островский    370
Тургенев      350
Чехов         450
Name: (p, min), dtype: int64

In [131]:
df_a_p['cover']=['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
df_a_p

a_i         a_n                   b_t    p    cover
0    1    Тургенев           Отцы и дети  450  твердая
1    1    Тургенев                 Рудин  300   мягкая
2    1    Тургенев     Дворянское гнездо  350   мягкая
3    2       Чехов      Толстый и тонкий  500  твердая
4    2       Чехов       Дама с собачкой  450  твердая
5    3  Островский                 Гроза  370   мягкая
6    3  Островский  Таланты и поклонники  290   мягкая

In [141]:
df_b_i=pd.pivot_table(df_a_p, index='a_n', columns='cover', values='p',aggfunc='sum', fill_value=0)
df_b_i

cover       мягкая  твердая
a_n                        
Островский     660        0
Тургенев       650      450
Чехов            0      950

In [142]:
df_b_i.to_pickle('book_info.pkl')

In [143]:
df_b_i2=pd.read_pickle('book_info.pkl')

In [144]:
df_b_i

cover       мягкая  твердая
a_n                        
Островский     660        0
Тургенев       650      450
Чехов            0      950